/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOrganizationsRouteRouteImport } from './routes/dashboard/organizations/route'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/dashboard/organizations/index'
import { Route as DashboardClinicsIndexRouteImport } from './routes/dashboard/clinics/index'
import { Route as DashboardBeneficiariesIndexRouteImport } from './routes/dashboard/beneficiaries/index'
import { Route as DashboardOrganizationsOrganizationIdRouteRouteImport } from './routes/dashboard/organizations/$organizationId/route'
import { Route as DashboardOrganizationsOrganizationIdIndexRouteImport } from './routes/dashboard/organizations/$organizationId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrganizationsRouteRoute =
  DashboardOrganizationsRouteRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)
const DashboardClinicsIndexRoute = DashboardClinicsIndexRouteImport.update({
  id: '/clinics/',
  path: '/clinics/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBeneficiariesIndexRoute =
  DashboardBeneficiariesIndexRouteImport.update({
    id: '/beneficiaries/',
    path: '/beneficiaries/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardOrganizationsOrganizationIdRouteRoute =
  DashboardOrganizationsOrganizationIdRouteRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => DashboardOrganizationsRouteRoute,
  } as any)
const DashboardOrganizationsOrganizationIdIndexRoute =
  DashboardOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsOrganizationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesIndexRoute
  '/dashboard/clinics': typeof DashboardClinicsIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/organizations/$organizationId/': typeof DashboardOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesIndexRoute
  '/dashboard/clinics': typeof DashboardClinicsIndexRoute
  '/dashboard/organizations': typeof DashboardOrganizationsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/organizations': typeof DashboardOrganizationsRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  '/dashboard/beneficiaries/': typeof DashboardBeneficiariesIndexRoute
  '/dashboard/clinics/': typeof DashboardClinicsIndexRoute
  '/dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/organizations/$organizationId/': typeof DashboardOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/organizations'
    | '/dashboard/'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/beneficiaries'
    | '/dashboard/clinics'
    | '/dashboard/organizations/'
    | '/dashboard/settings'
    | '/dashboard/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/beneficiaries'
    | '/dashboard/clinics'
    | '/dashboard/organizations'
    | '/dashboard/settings'
    | '/dashboard/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/organizations'
    | '/dashboard/'
    | '/dashboard/organizations/$organizationId'
    | '/dashboard/beneficiaries/'
    | '/dashboard/clinics/'
    | '/dashboard/organizations/'
    | '/dashboard/settings/'
    | '/dashboard/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations': {
      id: '/dashboard/organizations'
      path: '/organizations'
      fullPath: '/dashboard/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/': {
      id: '/dashboard/organizations/'
      path: '/'
      fullPath: '/dashboard/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardOrganizationsRouteRoute
    }
    '/dashboard/clinics/': {
      id: '/dashboard/clinics/'
      path: '/clinics'
      fullPath: '/dashboard/clinics'
      preLoaderRoute: typeof DashboardClinicsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/beneficiaries/': {
      id: '/dashboard/beneficiaries/'
      path: '/beneficiaries'
      fullPath: '/dashboard/beneficiaries'
      preLoaderRoute: typeof DashboardBeneficiariesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/organizations/$organizationId': {
      id: '/dashboard/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/dashboard/organizations/$organizationId'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdRouteRouteImport
      parentRoute: typeof DashboardOrganizationsRouteRoute
    }
    '/dashboard/organizations/$organizationId/': {
      id: '/dashboard/organizations/$organizationId/'
      path: '/'
      fullPath: '/dashboard/organizations/$organizationId/'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof DashboardOrganizationsOrganizationIdRouteRoute
    }
  }
}

interface DashboardOrganizationsOrganizationIdRouteRouteChildren {
  DashboardOrganizationsOrganizationIdIndexRoute: typeof DashboardOrganizationsOrganizationIdIndexRoute
}

const DashboardOrganizationsOrganizationIdRouteRouteChildren: DashboardOrganizationsOrganizationIdRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdIndexRoute:
      DashboardOrganizationsOrganizationIdIndexRoute,
  }

const DashboardOrganizationsOrganizationIdRouteRouteWithChildren =
  DashboardOrganizationsOrganizationIdRouteRoute._addFileChildren(
    DashboardOrganizationsOrganizationIdRouteRouteChildren,
  )

interface DashboardOrganizationsRouteRouteChildren {
  DashboardOrganizationsOrganizationIdRouteRoute: typeof DashboardOrganizationsOrganizationIdRouteRouteWithChildren
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
}

const DashboardOrganizationsRouteRouteChildren: DashboardOrganizationsRouteRouteChildren =
  {
    DashboardOrganizationsOrganizationIdRouteRoute:
      DashboardOrganizationsOrganizationIdRouteRouteWithChildren,
    DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  }

const DashboardOrganizationsRouteRouteWithChildren =
  DashboardOrganizationsRouteRoute._addFileChildren(
    DashboardOrganizationsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardOrganizationsRouteRoute: typeof DashboardOrganizationsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBeneficiariesIndexRoute: typeof DashboardBeneficiariesIndexRoute
  DashboardClinicsIndexRoute: typeof DashboardClinicsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardOrganizationsRouteRoute:
    DashboardOrganizationsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBeneficiariesIndexRoute: DashboardBeneficiariesIndexRoute,
  DashboardClinicsIndexRoute: DashboardClinicsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
